# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subject_sytem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='time',
        ),
        migrations.AddField(
            model_name='subject',
            name='time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subject_sytem.SubjectTime', verbose_name='上课时间'),
        ),
    ]
