# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-12-13 01:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import subject_system.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RelationStudentSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField(verbose_name='\u4e0a\u8bfe\u65e5\u671f')),
                ('create_time', models.DateTimeField(verbose_name='\u521b\u5efa\u65e5\u671f')),
            ],
            bases=(subject_system.models.ModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u59d3\u540d')),
            ],
            bases=(subject_system.models.ModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u8bfe\u7a0b\u540d\u79f0')),
            ],
            bases=(subject_system.models.ModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SubjectTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='\u4e0a\u8bfe\u65f6\u95f4')),
                ('end_time', models.TimeField(verbose_name='\u4e0b\u8bfe\u65f6\u95f4')),
            ],
            bases=(subject_system.models.ModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u59d3\u540d')),
            ],
            bases=(subject_system.models.ModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subject_system.Teacher', verbose_name='\u6559\u5e08\u59d3\u540d'),
        ),
        migrations.AddField(
            model_name='subject',
            name='time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subject_system.SubjectTime', verbose_name='\u4e0a\u8bfe\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='relationstudentsubject',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject_system.Student', verbose_name='\u5b66\u751f\u59d3\u540d'),
        ),
        migrations.AddField(
            model_name='relationstudentsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject_system.Subject', verbose_name='\u8bfe\u7a0b\u540d\u79f0'),
        ),
    ]
