#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Created by Alex on 2016/11/30
import xlsxwriter


def workbookexcel(name="test"):
    def action(excel):
        def openexcel(*args, **kwargs):
            workbook = xlsxwriter.Workbook(name + ".xlsx")
            worksheet = workbook.add_worksheet()
            result = excel(worksheet=worksheet, *args, **kwargs)
            workbook.close()
            return result

        return openexcel

    return action


@workbookexcel(name="test")
def writetoexcel(worksheet=None, tables=None):
    start = 1
    if isinstance(tables, dict):
        for tabname, table in tables.items():
            exporttable(worksheet, {tabname: table}, start)
            start += len(table)


def exporttable(worksheet=None, table=None, start=None):
    tablename = table.keys()[0]
    worksheet.write("A" + str(start), tablename)
    for row, culonm in enumerate(table[tablename]):
        worksheet.write("B" + str(row + start), culonm[0])
        worksheet.write("C" + str(row + start), culonm[3])
        worksheet.write("D" + str(row + start), culonm[1])


if __name__ == '__main__':
    table = {'car_customer': [('id', 'NO', 'int', 'int(11)'),
                              ('uuid', 'YES', 'varchar', 'varchar(32)'),
                              ('car', 'YES', 'varchar', 'varchar(32)'),
                              ('customer', 'YES', 'varchar', 'varchar(20)'),
                              ('createby', 'YES', 'int', 'int(11)'),
                              ('createon', 'YES', 'datetime', 'datetime'),
                              ('modifyby', 'YES', 'int', 'int(11)'),
                              ('modifyon', 'YES', 'datetime', 'datetime')],
             'person_queue': [('id', 'NO', 'int', 'int(11)'),
                              ('uuid', 'NO', 'varchar', 'varchar(64)'),
                              ('statu', 'YES', 'varchar', 'varchar(8)'),
                              ('person', 'YES', 'varchar', 'varchar(64)'),
                              ('company', 'YES', 'varchar', 'varchar(64)'),
                              ('create_by', 'YES', 'datetime', 'datetime'),
                              ('create_on', 'YES', 'int', 'int(11)'),
                              ('modify_by', 'YES', 'datetime', 'datetime'),
                              ('modify_on', 'YES', 'int', 'int(11)')],
             'Menu_group': [('id', 'NO', 'int', 'int(11)'),
                            ('group', 'NO', 'varchar', 'varchar(255)'),
                            ('note', 'YES', 'varchar', 'varchar(1000)')],
             'Inventory': [('id', 'NO', 'int', 'int(11)'),
                           ('cInvCode', 'YES', 'varchar', 'varchar(20)'),
                           ('cInvAddCode', 'YES', 'varchar', 'varchar(255)'),
                           ('cInvName', 'YES', 'varchar', 'varchar(255)'),
                           ('cInvCCode', 'YES', 'varchar', 'varchar(12)')],
             'Auth_membership': [('id', 'NO', 'int', 'int(11)'),
                                 ('user_id', 'NO', 'int', 'int(11)'),
                                 ('group_id', 'NO', 'int', 'int(11)')],
             'Test': [('id', 'NO', 'int', 'int(11)'),
                      ('content', 'YES', 'varchar', 'varchar(255)')],
             'Auth_user': [('id', 'NO', 'int', 'int(11)'),
                           ('username', 'YES', 'varchar', 'varchar(255)'),
                           ('password', 'YES', 'varchar', 'varchar(255)'),
                           ('registration_key', 'YES', 'varchar', 'varchar(255)'),
                           ('person_id', 'YES', 'int', 'int(11)'),
                           ('menu_group', 'YES', 'int', 'int(11)'),
                           ('company', 'YES', 'varchar', 'varchar(32)')],
             'Auth_event': [('id', 'NO', 'int', 'int(11)'),
                            ('time_stamp', 'NO', 'datetime', 'datetime'),
                            ('client_ip', 'NO', 'varchar', 'varchar(50)'),
                            ('user_id', 'YES', 'int', 'int(11)'),
                            ('origin', 'YES', 'varchar', 'varchar(255)'),
                            ('description', 'YES', 'varchar', 'varchar(1000)')],
             'Auth_permission': [('id', 'NO', 'int', 'int(11)'),
                                 ('group_id', 'YES', 'int', 'int(11)'),
                                 ('name', 'YES', 'varchar', 'varchar(512)'),
                                 ('table_name', 'YES', 'varchar', 'varchar(512)'),
                                 ('record_id', 'YES', 'int', 'int(11)'),
                                 ('stat', 'YES', 'varchar', 'varchar(8)')],
             'Auth_group': [('id', 'NO', 'int', 'int(11)'),
                            ('role', 'NO', 'varchar', 'varchar(255)'),
                            ('description', 'YES', 'varchar', 'varchar(1000)')],
             'car_point': [('id', 'NO', 'int', 'int(11)'),
                           ('uuid', 'YES', 'varchar', 'varchar(32)'),
                           ('car', 'YES', 'varchar', 'varchar(32)'),
                           ('car_plan', 'YES', 'varchar', 'varchar(32)'),
                           ('order_numb', 'YES', 'int', 'int(11)'),
                           ('isarrived', 'YES', 'varchar', 'varchar(8)'),
                           ('createby', 'YES', 'int', 'int(11)'),
                           ('createon', 'YES', 'datetime', 'datetime'),
                           ('modifyby', 'YES', 'int', 'int(11)'),
                           ('modifyon', 'YES', 'datetime', 'datetime')],
             'Auth_menu': [('id', 'NO', 'int', 'int(11)'),
                           ('groupid', 'NO', 'int', 'int(11)'),
                           ('oder', 'NO', 'int', 'int(11)'),
                           ('icon', 'YES', 'varchar', 'varchar(100)'),
                           ('perant', 'YES', 'int', 'int(11)'),
                           ('title', 'NO', 'varchar', 'varchar(100)'),
                           ('link', 'YES', 'varchar', 'varchar(200)'),
                           ('createby', 'YES', 'int', 'int(11)'),
                           ('createon', 'YES', 'datetime', 'datetime'),
                           ('modifyby', 'YES', 'int', 'int(11)'),
                           ('modifyon', 'YES', 'datetime', 'datetime'),
                           ('state', 'YES', 'varchar', 'varchar(8)')],
             'car_plan': [('id', 'NO', 'int', 'int(11)'),
                          ('uuid', 'YES', 'varchar', 'varchar(32)'),
                          ('car', 'YES', 'varchar', 'varchar(32)'),
                          ('transfer_plan', 'YES', 'varchar', 'varchar(32)'),
                          ('path', 'YES', 'varchar', 'varchar(32)'),
                          ('cargo', 'YES', 'varchar', 'varchar(64)'),
                          ('load', 'YES', 'decimal', 'decimal(10,0)'),
                          ('re_load', 'YES', 'decimal', 'decimal(10,0)'),
                          ('task_type', 'YES', 'varchar', 'varchar(8)'),
                          ('isback', 'YES', 'varchar', 'varchar(8)'),
                          ('driver', 'YES', 'varchar', 'varchar(32)'),
                          ('pupercargo', 'YES', 'varchar', 'varchar(32)'),
                          ('car_confirm', 'YES', 'varchar', 'varchar(8)'),
                          ('driver_confirm', 'YES', 'varchar', 'varchar(8)'),
                          ('pupercargo_confirm', 'YES', 'varchar', 'varchar(8)'),
                          ('isfinished', 'YES', 'varchar', 'varchar(8)'),
                          ('isdelete', 'YES', 'varchar', 'varchar(8)'),
                          ('createby', 'YES', 'int', 'int(11)'),
                          ('createon', 'YES', 'datetime', 'datetime'),
                          ('modifyby', 'YES', 'int', 'int(11)'),
                          ('modifyon', 'YES', 'datetime', 'datetime'),
                          ('customer', 'YES', 'varchar', 'varchar(20)')],
             'car_queue': [('id', 'NO', 'int', 'int(11)'),
                           ('uuid', 'YES', 'varchar', 'varchar(32)'),
                           ('car', 'YES', 'varchar', 'varchar(32)'),
                           ('beidou', 'YES', 'varchar', 'varchar(64)'),
                           ('statu', 'YES', 'varchar', 'varchar(8)'),
                           ('rank', 'YES', 'decimal', 'decimal(10,0)'),
                           ('company', 'YES', 'varchar', 'varchar(32)'),
                           ('createby', 'YES', 'int', 'int(11)'),
                           ('createon', 'YES', 'datetime', 'datetime'),
                           ('modifyby', 'YES', 'int', 'int(11)'),
                           ('modifyon', 'YES', 'datetime', 'datetime'),
                           ('cargo_id', 'YES', 'varchar', 'varchar(60)')],
             'Customer': [('id', 'NO', 'int', 'int(11)'),
                          ('cCusCode', 'YES', 'varchar', 'varchar(20)'),
                          ('cCusAbbName', 'YES', 'varchar', 'varchar(60)'),
                          ('cCusName', 'YES', 'varchar', 'varchar(98)'),
                          ('cCCCode', 'YES', 'varchar', 'varchar(12)'),
                          ('latitude', 'YES', 'decimal', 'decimal(10,0)'),
                          ('longitude', 'YES', 'decimal', 'decimal(10,0)'),
                          ('isdelete', 'YES', 'varchar', 'varchar(8)'),
                          ('createby', 'YES', 'int', 'int(11)'),
                          ('createon', 'YES', 'datetime', 'datetime'),
                          ('modifyby', 'YES', 'int', 'int(11)'),
                          ('modifyon', 'YES', 'datetime', 'datetime')],
             'transfer_plan': [('id', 'NO', 'int', 'int(11)'),
                               ('uuid', 'NO', 'varchar', 'varchar(32)'),
                               ('customer', 'YES', 'varchar', 'varchar(32)'),
                               ('path', 'YES', 'varchar', 'varchar(32)'),
                               ('cout_product', 'YES', 'decimal', 'decimal(3,0)'),
                               ('cargo_id', 'YES', 'varchar', 'varchar(64)'),
                               ('isdelete', 'YES', 'varchar', 'varchar(8)'),
                               ('ischecked', 'YES', 'varchar', 'varchar(8)'),
                               ('statu', 'YES', 'varchar', 'varchar(8)'),
                               ('createby', 'YES', 'int', 'int(11)'),
                               ('createon', 'YES', 'datetime', 'datetime'),
                               ('modifyby', 'YES', 'int', 'int(11)'),
                               ('modifyon', 'YES', 'datetime', 'datetime'),
                               ('company', 'YES', 'varchar', 'varchar(32)')],
             'beidou': [('id', 'NO', 'int', 'int(11)'),
                        ('beidou_indentifier', 'YES', 'varchar', 'varchar(64)'),
                        ('code', 'YES', 'varchar', 'varchar(255)'),
                        ('statu', 'YES', 'varchar', 'varchar(8)'),
                        ('createby', 'YES', 'int', 'int(11)'),
                        ('createon', 'YES', 'datetime', 'datetime'),
                        ('modifyby', 'YES', 'int', 'int(11)'),
                        ('modifyon', 'YES', 'datetime', 'datetime')],
             'IdentifierCode': [('id', 'NO', 'int', 'int(11)'),
                                ('inputDistinguish', 'YES', 'varchar', 'varchar(255)'),
                                ('inputState', 'YES', 'varchar', 'varchar(255)'),
                                ('inputRemark', 'YES', 'varchar', 'varchar(255)')],
             'car': [('id', 'NO', 'int', 'int(11)'),
                     ('uuid', 'YES', 'varchar', 'varchar(36)'),
                     ('license_plate', 'YES', 'varchar', 'varchar(60)'),
                     ('conpany', 'YES', 'varchar', 'varchar(255)'),
                     ('cargo_id', 'YES', 'varchar', 'varchar(60)'),
                     ('company', 'YES', 'varchar', 'varchar(32)'),
                     ('pic_front', 'YES', 'varchar', 'varchar(255)'),
                     ('pic_back', 'YES', 'varchar', 'varchar(255)'),
                     ('pic_side', 'YES', 'varchar', 'varchar(255)'),
                     ('load', 'YES', 'decimal', 'decimal(10,3)'),
                     ('tare', 'YES', 'decimal', 'decimal(10,3)'),
                     ('ischecked', 'YES', 'varchar', 'varchar(8)'),
                     ('isdelete', 'YES', 'varchar', 'varchar(8)'),
                     ('beidou_id', 'YES', 'varchar', 'varchar(64)'),
                     ('createby', 'YES', 'int', 'int(11)'),
                     ('createon', 'YES', 'datetime', 'datetime'),
                     ('modifyby', 'YES', 'int', 'int(11)'),
                     ('modifyon', 'YES', 'datetime', 'datetime')],
             'person': [('id', 'NO', 'int', 'int(11)'),
                        ('uuid', 'NO', 'varchar', 'varchar(32)'),
                        ('name', 'NO', 'varchar', 'varchar(60)'),
                        ('gender', 'YES', 'varchar', 'varchar(2)'),
                        ('company', 'YES', 'varchar', 'varchar(32)'),
                        ('id_number', 'YES', 'varchar', 'varchar(20)'),
                        ('phone_number', 'YES', 'varchar', 'varchar(11)'),
                        ('id_pic_front', 'YES', 'varchar', 'varchar(200)'),
                        ('id_pic_back', 'YES', 'varchar', 'varchar(200)'),
                        ('isdelete', 'YES', 'varchar', 'varchar(8)'),
                        ('iscompany', 'YES', 'varchar', 'varchar(8)'),
                        ('ischecked', 'NO', 'varchar', 'varchar(8)'),
                        ('creatby', 'YES', 'int', 'int(11)'),
                        ('creaton', 'YES', 'datetime', 'datetime'),
                        ('modifyby', 'YES', 'int', 'int(11)'),
                        ('modifyon', 'YES', 'varchar', 'varchar(255)')],
             'transport_company': [('id', 'NO', 'int', 'int(11)'),
                                   ('uuid', 'YES', 'varchar', 'varchar(36)'),
                                   ('name', 'YES', 'varchar', 'varchar(200)'),
                                   ('abbname', 'YES', 'varchar', 'varchar(100)'),
                                   ('isdelete', 'YES', 'varchar', 'varchar(8)'), (
                                       'legal_person_name', 'YES', 'varchar',
                                       'varchar(100)'),
                                   ('contract_numb', 'YES', 'varchar', 'varchar(200)'),
                                   ('createby', 'YES', 'int', 'int(11)'),
                                   ('createon', 'YES', 'datetime', 'datetime'),
                                   ('modifyby', 'YES', 'int', 'int(11)'),
                                   ('modifyon', 'YES', 'datetime', 'datetime')],
             'car_plan_confirm': [('id', 'NO', 'int', 'int(11)'),
                                  ('uuid', 'YES', 'varchar', 'varchar(32)'),
                                  ('car_plan', 'YES', 'varchar', 'varchar(32)'),
                                  ('confirm_result', 'YES', 'varchar', 'varchar(8)'),
                                  ('note', 'YES', 'varchar', 'varchar(255)'),
                                  ('createby', 'YES', 'int', 'int(11)'),
                                  ('createon', 'YES', 'datetime', 'datetime'),
                                  ('modifyby', 'YES', 'int', 'int(11)'),
                                  ('modifyon', 'YES', 'datetime', 'datetime')],
             'sys_cron_task': [('id', 'NO', 'int', 'int(11)'),
                               ('name', 'NO', 'varchar', 'varchar(255)'),
                               ('group', 'NO', 'varchar', 'varchar(255)'),
                               ('cron', 'NO', 'varchar', 'varchar(50)'),
                               ('classpath', 'NO', 'varchar', 'varchar(255)'),
                               ('statu', 'YES', 'varchar', 'varchar(8)')]}

    writetoexcel(tables=table)
